- name: Copy mongodb repo file
  ansible.builtin.copy:
   src: mongodb.repo
   dest: /etc/yum.repos.d/mongodb.repo

- name: Install Mongodb client
  ansible.builtin.yum:
   name: mongodb-org-shell
   state: installed

- name: Load load_schema
  ansible.builtin.shell: mongo --host mongodb.imrankhandevops72.online </app/schema/{{ component }}.js