
- name: Install mysql client
  ansible.builtin.yum:
   name: mysql
   state: installed

ABDUL
 OSAMA
 
- name: Load Schema
  ansible.builtin.shell: mysql --host mysql.imrankhandevops72.online -uroot -pRoboShop@1 </app/schema/{{ component }}.sql
