- name: copy systemd file
  ansible.builtin.copy:
    src: "{{ c }}.service"
    dest: /etc/systemd/system/{{ component }}.service

- name: start {{ compnent }} service
  ansible.builtin.systemd:
    name: "{{ component}}"
    state: restarted
    enabled: yes
    daemon-reload: yes